### ISSUE TITLE
Default date format not supported

### ISSUE THREAD

**Issue by alarsyo** [ArthurFDLR/beancount-ce#2]
Hey! First of all, thanks for this useful package :) you've saved me quite some time already in the last few years.

The latest caisse d'épargne CSV exporter seems to offer two choices for date formats, one being  `%d/%m/%Y` and the other `%Y/%m/%d`; the first one is the default dialogue choice, and [is currently not listed in supported date formats](https://github.com/ArthurFDLR/beancount-ce/blob/5b706104e144b7ae925d6eae115c11f2218ad7c1/beancount_ce/importer_csv.py#L14). A workaround is to simply ask for the second date format, which is supported by beancount-ce, thankfully.

![image](https://user-images.githubusercontent.com/15170378/198619420-4394ce80-0049-48eb-9ae1-d33201a515e1.png)

**Comment by ArthurFDLR** [comment]
Hey, thanks for the heads-up! The file format changes every few months.
I updated CSV's default date format in the new package version (v2.1.0). Both date formats in the CSV exporter should be automatically detected now.
Feel free to re-open the issue if v1.1.0 doesn't fix your problem.
